### ISSUE TITLE
Error in compile

### ISSUE THREAD

**Issue by Revozop** [ChadMotivation/TymSpecial#1]
![image](https://user-images.githubusercontent.com/91875992/153980260-c388e97a-859a-428d-8185-987ca225167e.png)

After it the file is not compiled

**Comment by ChadMotivation** [comment]
The issue here is that your compiling on Windows. The script uses g++ to compile and on Linux for some reason not all structures/functions are defined. So the structure for STARTUPINFOEXA is defined specifically in the syscalls.h header file. 
On Windows it is able to find that structure so theres now two definitions.

See below in syscalls.h
![reply](https://user-images.githubusercontent.com/45154327/153983501-e86679c7-0a54-4b9f-ae42-16dbe3892276.png)


Im going to add to the readme this is only for Linux

**Comment by nemesis7331** [comment]
I have a similar issue on Kali :/

```
└─$ python3 TymSpecial.py --input msgbox.shellcode --out out.exe --method 2
[+] Successfully read shellcode file
[+] Successfully generated XOR key of : UOzmgYi
[+] Execution method 2 selected
[+] C++ stub written to disk: temp.cpp
In file included from temp.cpp:5:
syscalls.h:21:16: error: redefinition of ‘struct _STARTUPINFOEXA’
   21 | typedef struct _STARTUPINFOEXA {
      |                ^~~~~~~~~~~~~~~
In file included from /usr/share/mingw-w64/include/windows.h:70,
                 from temp.cpp:2:
/usr/share/mingw-w64/include/winbase.h:1526:18: note: previous definition of ‘struct _STARTUPINFOEXA’
 1526 |   typedef struct _STARTUPINFOEXA {
      |                  ^~~~~~~~~~~~~~~
In file included from temp.cpp:5:
syscalls.h:24:3: error: conflicting declaration ‘typedef int STARTUPINFOEXA’
   24 | } STARTUPINFOEXA, *LPSTARTUPINFOEXA;
      |   ^~~~~~~~~~~~~~
In file included from /usr/share/mingw-w64/include/windows.h:70,
                 from temp.cpp:2:
/usr/share/mingw-w64/include/winbase.h:1529:5: note: previous declaration as ‘typedef struct _STARTUPINFOEXA STARTUPINFOEXA’
 1529 |   } STARTUPINFOEXA,*LPSTARTUPINFOEXA;
      |     ^~~~~~~~~~~~~~
In file included from temp.cpp:5:
syscalls.h:24:20: error: conflicting declaration ‘typedef int* LPSTARTUPINFOEXA’
   24 | } STARTUPINFOEXA, *LPSTARTUPINFOEXA;
      |                    ^~~~~~~~~~~~~~~~
In file included from /usr/share/mingw-w64/include/windows.h:70,
                 from temp.cpp:2:
/usr/share/mingw-w64/include/winbase.h:1529:21: note: previous declaration as ‘typedef struct _STARTUPINFOEXA* LPSTARTUPINFOEXA’
 1529 |   } STARTUPINFOEXA,*LPSTARTUPINFOEXA;
      |                     ^~~~~~~~~~~~~~~~
[+] C++ stub compiled & temporary stub removed
```

**Comment by ChadMotivation** [comment]
@nemesis7331 I'm not maintaining this repo so I wont be making any changes but I believe the issue here is that on your Kali box your header files have a definition for those structures already, where as when I made this my system did not so I had to manually define them.

You can try to delete the definitions from the TymSpecial source code since they already exist and shouldn't be needed and hopefully that should fix it. Personally though I prefer to compile in Visual Studio (i just made this as a PoC script so I had to use gcc/g++).

**Comment by ChadMotivation** [comment]
Also these are all pretty signatured now, if your looking to use this in actual testing I'd prob recommend copying the source code, generating assembly stubs via SysWhispers3 (https://github.com/klezVirus/SysWhispers3) and compiling in Visual Studio. Or using ScareCrow.
